#+TITLE: 一键安装最新内核并开启 BBR 脚本

最近，Google 开源了其 TCP BBR 拥塞控制算法，并提交到了 Linux 内核，最新的 4.9 版
内核已经用上了该算法。根据以往的传统，Google 总是先在自家的生产环境上线运用后，
才会将代码开源，此次也不例外。
根据实地测试，在部署了最新版内核并开启了 TCP BBR 的机器上，网速甚至可以提升好几个
数量级。
于是我根据目前三大发行版的最新内核，开发了一键安装最新内核并开启 TCP BBR 脚本。

* 本脚本适用环境
- 系统支持：CentOS 6+，Debian 7+，Ubuntu 12+
- 虚拟技术：OpenVZ 以外的（KVM、Xen、VMware 等）
- 内存要求：≥128M
日期　　：2016 年 12 月 24 日

* 关于本脚本
1. 本脚本已在 [[https://www.vultr.com/?ref=6914340-3B][Vultr]] 上的 VPS 全部测试通过。
2. 当脚本检测到 VPS 的虚拟方式为 OpenVZ 时，会提示错误，并自动退出安装。
3. 某些服务商（如 [[https://www.digitalocean.com/community/tutorials/how-to-update-a-digitalocean-server-s-kernel][DigitalOcean]] ）可能需要首先将 VPS 配置为可自定义内核，
   然后 grub2 的配置才会生效。
4. 脚本运行完重启发现开不了机的，打开 VPS 后台控制面板的 VNC, 开机卡在 grub
   引导, 手动选择内核即可。
5. 由于是使用最新版系统内核，最好请勿在生产环境安装，以免产生不可预测之后果。

* 使用方法
使用 root 用户登录，运行以下命令：
#+BEGIN_SRC bash
wget --no-check-certificate https://github.com/teddysun/across/raw/master/bbr.sh
chmod +x bbr.sh
./bbr.sh
#+END_SRC

安装完成后，脚本会提示需要重启 VPS，输入 y 并回车后重启。
重启完成后，进入 VPS，验证一下是否成功安装最新内核并开启 TCP BBR，输入以下命令：
#+BEGIN_SRC bash
uname -r
#+END_SRC

查看内核版本，含有 4.9.0 就表示 OK 了
#+BEGIN_SRC bash
sysctl net.ipv4.tcp_available_congestion_control
#+END_SRC

返回值一般为：
net.ipv4.tcp_available_congestion_control = bbr cubic reno

#+BEGIN_SRC bash
sysctl net.ipv4.tcp_congestion_control
#+END_SRC

返回值一般为：
net.ipv4.tcp_congestion_control = bbr

#+BEGIN_SRC bash
sysctl net.core.default_qdisc
#+END_SRC

返回值一般为：
net.core.default_qdisc = fq

#+BEGIN_SRC bash
lsmod | grep bbr
#+END_SRC

返回值有 tcp_bbr 模块即说明 bbr 已启动。

* 参考链接：
- https://github.com/google/bbr/blob/master/Documentation/bbr-quick-start.md
- http://elrepo.org/tiki/tiki-index.php
- http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.9/
